parserOptions:
  ecmaVersion: 2018

env:
  es6: true
  node: true
  jest: true

extends: "htmlacademy/node"

ignorePatterns: "**/express/public/**/*.js"

rules:
  "object-curly-spacing": [2, "always"]
